version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "yourpassword"
      MYSQL_DATABASE: yourdbname
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-pyourpassword"]
      interval: 10s
      retries: 10
      timeout: 5s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-springboot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/yourdbname
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "yourpassword"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-net

volumes:
  mysql_data:

networks:
  app-net: